# The west manifest file for the Pinetime.
#
# The per-installation west configuration file specifies the location of this
# manifest file. The "path" option in the [manifest] section of .west/config
# defines the folder that contains west.yml. The path is relative to the folder
# that contains .west.
#
# You can create your own manifest files and put them in any
# repository you want, to create your own custom Pinetime installation.
# For example, you could create a manifest file in your own
# out-of-tree application directory, which would pull the pinetime repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new pinetime installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: pinetime

  remotes:
    - name: ncs
      url-base: https://github.com/NordicPlayground
    - name: pinetime
      url-base: https://github.com/nordic-krch
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: armmbed
      url-base: https://github.com/ARMmbed

  # The list of external projects for the Pinetime.
  #
  projects:
    - name: nrf
      repo-path: fw-nrfconnect-nrf
      west-commands: scripts/west-commands.yml
      revision: d43664e241668d6b6e989a1f7785f8715a9f9671
      remote: ncs
    - name: zephyr
      west-commands: scripts/west-commands.yml
      revision: cbe6edcfa7049d02b8f2215abc8ccb828c86d646
      remote: zephyrproject
    - name: fatfs
      revision: 0c1288bb817c1976388e0f55e8483f671ae437ab
      path: modules/fs/fatfs
      remote: zephyrproject
    - name: hal_nordic
      revision: 8506c348b6da91a9f53bcbb181ecd82b752b9eed
      path: modules/hal/nordic
      remote: zephyrproject
    - name: libmetal
      revision: 45e630d6152824f807d3f919958605c4626cbdff
      path: modules/hal/libmetal
      remote: zephyrproject
    - name: lvgl
      revision: 74fc2e753a997bd71cefa34dd9c56dcb954b42e2
      path: modules/lib/gui/lvgl
      remote: zephyrproject
    - name: mbedtls
      revision: 3776c158fe138a72c97c187e4d31c81c37884be9
      path: modules/crypto/mbedtls
      remote: zephyrproject
    - name: mcuboot
      repo-path: fw-nrfconnect-mcuboot
      revision: 0b59f48e4dce86d0c8d4e09688feb362c7223ad3
      remote: ncs
    - name: mcumgr
      repo-path: fw-nrfconnect-mcumgr
      revision: f663988d35da559a37f263d369842dbce309d1fa
      path: modules/lib/mcumgr
      remote: ncs
    - name: net-tools
      revision: 30b7efa827b04d2e47840716b0372737fe7d6c92
      path: tools/net-tools
      remote: zephyrproject
    - name: nffs
      revision: 00dd4fab1a00f2f6e995ef3f2e7c3814689f8885
      path: modules/fs/nffs
      remote: zephyrproject
    - name: open-amp
      revision: 9b591b289e1f37339bd038b5a1f0e6c8ad39c63a
      path: modules/lib/open-amp
      remote: zephyrproject
    - name: segger
      revision: 6fcf61606d6012d2c44129edc033f59331e268bc
      path: modules/debug/segger
      remote: zephyrproject
    - name: tinycbor
      path: modules/lib/tinycbor
      revision: 0fc68fceacd1efc1ce809c5880c380f3d98b7b6e
      remote: zephyrproject
    - name: littlefs
      path: modules/fs/littlefs
      revision: fe9572dd5a9fcf93a249daa4233012692bd2881d
      remote: zephyrproject
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      revision: baf51863f19f009b92e762115ba5572a5b996b92
      remote: zephyrproject
    - name: nrf_hw_models
      path: modules/bsim_hw_models/nrf_hw_models
      revision: fec69703cb1ca06fcdab6d5fde01274f0fc5c759
      remote: zephyrproject
    - name: edtt
      path: tools/edtt
      revision: dd4dd502ef2fbeced6ef7faaba562a7ddca45632
      remote: zephyrproject

  self:
    path: pinetime
